# Generated by Django 5.2.7 on 2025-10-14 10:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.utils.generators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("schemes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.core.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When record was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When record was last updated."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        help_text="Business or operational status of this record.",
                        max_length=10,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Indicates if record is soft deleted."
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="When record was soft deleted.", null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the person", max_length=200
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="National ID must contain only uppercase letters and numbers",
                                regex="^[A-Z0-9]+$",
                            )
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("SELF", "Self"),
                            ("SPOUSE", "Spouse"),
                            ("CHILD", "Child"),
                        ],
                        db_index=True,
                        default="SELF",
                        max_length=20,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "card_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Card number must contain only uppercase letters, numbers and hyphens",
                                regex="^[A-Z0-9-]+$",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format: +999999999",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Associated company",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted the record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependants",
                        to="members.person",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        help_text="Insurance scheme",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schemes.scheme",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "scheme"],
                        name="members_per_company_03e582_idx",
                    ),
                    models.Index(
                        fields=["company", "card_number"],
                        name="members_per_company_50022b_idx",
                    ),
                    models.Index(
                        fields=["date_of_birth", "relationship"],
                        name="members_per_date_of_1d397f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "card_number"),
                        name="uniq_company_card_number",
                    )
                ],
            },
        ),
    ]
