# Generated by Django 5.2.7 on 2025-10-15 11:27

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("medical_catalog", "0001_initial"),
        ("providers", "0003_alter_doctor_license_number_alter_hospital_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="labtest",
            options={"verbose_name": "Lab Test", "verbose_name_plural": "Lab Tests"},
        ),
        migrations.AlterField(
            model_name="hospitalitemprice",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="labtest",
            name="base_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="labtest",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="base_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="medicine",
            unique_together={("name", "dosage_form")},
        ),
        migrations.AddIndex(
            model_name="hospitalitemprice",
            index=models.Index(
                fields=["hospital", "content_type", "object_id"],
                name="hospital_it_hospita_45fd5d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="hospitalitemprice",
            constraint=models.UniqueConstraint(
                fields=("hospital", "content_type", "object_id"),
                name="uniq_hospital_item_price",
            ),
        ),
    ]
