# Generated by Django 5.2.7 on 2025-10-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0002_remove_doctor_hospital_doctorhospitalaffiliation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="license_number",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
