# Generated by Django 5.1.4 on 2025-10-31 10:28

import apps.core.utils.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0003_alter_doctor_license_number_alter_hospital_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number in format: +[country code][number] (e.g., +12345678900).",
                max_length=20,
                validators=[apps.core.utils.validators.PhoneNumberValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="branch_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="branches",
                to="providers.hospital",
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number in format: +[country code][number] (e.g., +12345678900).",
                max_length=20,
                validators=[apps.core.utils.validators.PhoneNumberValidator()],
            ),
        ),
    ]
