"""
Django settings for ultra project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    # Load .env file from the backend directory
    env_path = BASE_DIR / '.env'
    if env_path.exists():
        load_dotenv(env_path)
except ImportError:
    # python-dotenv not installed, skip loading .env file
    pass

# Test detection - centralized for use across the application
IS_TESTING = 'test' in sys.argv or 'pytest' in sys.modules


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Parse DEBUG from environment with support for common truthy tokens
# Default to True for development convenience
_debug_value = os.environ.get('DEBUG', 'True').strip().lower()
DEBUG = _debug_value in ('1', 'true', 'yes', 'y', 't')

# Check for production environment flag
IS_PRODUCTION = os.environ.get('ENVIRONMENT', '').lower() in ('production', 'prod')

# SECURITY WARNING: keep the secret key used in production secret!
# Read SECRET_KEY from environment - no default for security
secret_key = os.environ.get('SECRET_KEY', '').strip()

# In production, SECRET_KEY must be set and non-empty
if IS_PRODUCTION and not secret_key:
    raise ImproperlyConfigured(
        "SECRET_KEY must be set as an environment variable when running in production. "
        "Set ENVIRONMENT=production requires a valid SECRET_KEY."
    )

# Use development default only when DEBUG is true
if not secret_key:
    if DEBUG:
        secret_key = 'django-insecure-bo-cm(8%s0lu^$5snvv)!guhe00lyh&!qx7xil5%c8bs3_c7gd'  # Development default only
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY must be set whenever DEBUG=False. "
            "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
        )

SECRET_KEY = secret_key

# Parse ALLOWED_HOSTS from environment variable (comma-separated)
ALLOWED_HOSTS = [
    host.strip() for host in os.environ.get(
        'ALLOWED_HOSTS',
        'localhost,127.0.0.1,0.0.0.0,testserver'
    ).split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_filters",
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
    "apps.core",
    "apps.companies",
    "apps.schemes",
    "apps.members",
    "apps.providers",
    "apps.medical_catalog",
    "apps.claims",
]

MIDDLEWARE = [
    "apps.core.middleware.RequestIDMiddleware",  # Request ID tracking - must be early
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ultra.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ultra.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Support DATABASE_URL environment variable (e.g., for Xata, Heroku, etc.)
# Format: postgresql://user:password@host:port/database?sslmode=require
# If DATABASE_URL is not set, fall back to SQLite for development
database_url = os.environ.get('DATABASE_URL', '').strip()

if database_url:
    # Parse DATABASE_URL
    import urllib.parse
    result = urllib.parse.urlparse(database_url)
    
    # Extract database name (may include branch like "ultra:dev")
    db_path = result.path.lstrip('/')
    # Handle Xata format: "ultra:dev" -> use "ultra" as database name
    db_name = db_path.split(':')[0] if ':' in db_path else db_path
    
    # Parse query parameters
    query_params = urllib.parse.parse_qs(result.query)
    
    # Always require SSL for cloud databases (Xata, Heroku, etc.)
    # Use sslmode from URL if provided, otherwise default to 'require'
    ssl_mode = query_params.get('sslmode', ['require'])[0]
    
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": db_name,
            "USER": result.username,
            "PASSWORD": result.password,
            "HOST": result.hostname,
            "PORT": result.port or "5432",
            "OPTIONS": {
                "sslmode": ssl_mode,
            },
            # Use SQLite for tests (Xata doesn't support CREATE DATABASE)
            # This allows tests to run without trying to create test databases
            "TEST": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": ":memory:",
            },
        }
    }
else:
    # Fall back to SQLite for local development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Caching (Redis - fallback to local memory if Redis not available)
if DEBUG:
    # Use local memory cache in development
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }
else:
    # Use Redis in production
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": "redis://127.0.0.1:6379/1",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS Configuration
# In development, CORS_ALLOW_ALL_ORIGINS can be True for convenience
# In production, ALWAYS set to False and specify CORS_ALLOWED_ORIGINS
_cors_allow_all_origins_value = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'False').strip().lower()
CORS_ALLOW_ALL_ORIGINS = _cors_allow_all_origins_value in ('1', 'true', 'yes', 'y', 't')
CORS_ALLOW_CREDENTIALS = True

# Specific origins for production (set via CORS_ALLOWED_ORIGINS environment variable)
# If CORS_ALLOW_ALL_ORIGINS is False, this list will be used
if not CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        origin.strip() for origin in os.environ.get(
            'CORS_ALLOWED_ORIGINS',
            'http://localhost:5173,http://127.0.0.1:5173'
        ).split(',')
        if origin.strip()
    ]

# CSRF Trusted Origins - Required for CSRF protection to accept requests from these origins
# This is separate from CORS and is needed for Django's CSRF middleware
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173,http://localhost:8000,http://127.0.0.1:8000'
    ).split(',')
    if origin.strip()
]

# Session and CSRF Cookie Settings
# In development (DEBUG=True), cookies don't need to be secure (HTTP is OK)
# In production (DEBUG=False), cookies must be secure (HTTPS only)
SESSION_COOKIE_SECURE = not DEBUG  # Secure cookies only in production
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookies
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection while allowing cross-site navigation

CSRF_COOKIE_SECURE = not DEBUG  # Secure cookies only in production
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token (needed for X-CSRFToken header)
CSRF_COOKIE_SAMESITE = 'Lax'  # CSRF protection while allowing cross-site navigation

# CORS headers to allow
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CORS methods to allow
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

TEST_RUNNER = 'django.test.runner.DiscoverRunner'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'request_id': {
            '()': 'apps.core.utils.logging_filters.RequestIDFilter',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} [{request_id}] {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'filters': ['request_id'],
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'apps.core.exceptions': {
            'handlers': ['console'],
            'level': 'WARNING',  # Suppress ERROR logs for expected validation errors during tests
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# During tests, suppress validation/integrity error logging and request warnings
if IS_TESTING:
    LOGGING['loggers']['apps.core.exceptions']['level'] = 'CRITICAL'
    LOGGING['loggers']['django.request'] = {
        'handlers': ['console'],
        'level': 'ERROR',  # Suppress WARNING level logs like "Bad Request" during tests
        'propagate': False,
    }

# Determine default permission class from environment
# For development: set DEFAULT_PERMISSION_CLASS=AllowAny
# For production: set DEFAULT_PERMISSION_CLASS=IsAuthenticated (default)
_permission_class = os.environ.get('DEFAULT_PERMISSION_CLASS', 'IsAuthenticated')
_permission_mapping = {
    'AllowAny': 'rest_framework.permissions.AllowAny',
    'IsAuthenticated': 'rest_framework.permissions.IsAuthenticated',
}

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "EXCEPTION_HANDLER": "apps.core.exceptions.custom_exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        _permission_mapping.get(_permission_class, 'rest_framework.permissions.IsAuthenticated'),
    ],
    # Rate limiting / throttling
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/day",
        "burst": "10/minute",
        "strict": "20/hour",
        "anon_burst": "10/minute",
        "export": "5/hour",
    },
    # OpenAPI schema generation
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# OpenAPI/Swagger schema customization
SPECTACULAR_SETTINGS = {
    "TITLE": "Ultra Health Insurance API",
    "DESCRIPTION": (
        "Comprehensive health insurance management system providing "
        "APIs for companies, insurance schemes, members, healthcare providers, "
        "medical catalogs, and claims processing."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "CONTACT": {
        "name": "API Support",
        "email": "api-support@ultra-insurance.example",
    },
    "LICENSE": {
        "name": "Proprietary",
    },
    "TAGS": [
        {"name": "Authentication", "description": "Login, logout, CSRF token operations"},
        {"name": "Companies", "description": "Company and industry management"},
        {"name": "Schemes", "description": "Insurance schemes, plans, and benefits"},
        {"name": "Members", "description": "Member enrollment and management"},
        {"name": "Providers", "description": "Healthcare providers (hospitals, doctors)"},
        {"name": "Medical Catalog", "description": "Medical services, medicines, and lab tests"},
        {"name": "Claims", "description": "Insurance claim submission and processing"},
        {"name": "Health", "description": "System health check endpoints"},
    ],
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": False,
    },
    "COMPONENT_SPLIT_REQUEST": True,
}
