# Generated by Django 5.1.4 on 2025-10-24 22:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("schemes", "0002_alter_schemeitem_copayment_percent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefit",
            name="limit_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Coverage or limit amount.",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="limit_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Coverage or limit amount.",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="schemeitem",
            name="content_type",
            field=models.ForeignKey(
                help_text="Associated plan, benefit, hospital, service, lab test, or medicine.",
                limit_choices_to=models.Q(
                    models.Q(
                        ("app_label", "schemes"), ("model__in", ["plan", "benefit"])
                    ),
                    models.Q(("app_label", "providers"), ("model__in", ["hospital"])),
                    models.Q(
                        ("app_label", "medical_catalog"),
                        ("model__in", ["service", "labtest", "medicine"]),
                    ),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
