# Generated by Django 5.1.4 on 2025-10-24 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "schemes",
            "0003_alter_benefit_limit_amount_alter_scheme_limit_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="benefit",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Plan this benefit belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schemes.plan",
            ),
        ),
    ]
