# Generated by Django 5.1.4 on 2025-10-24 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schemes", "0004_add_plan_to_benefit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefit",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Plan this benefit belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="benefits",
                to="schemes.plan",
            ),
        ),
    ]
