# Generated by Django 5.1.4 on 2025-10-31 10:28

import apps.core.utils.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schemes", "0006_auto_20251024_2339"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefit",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Plan this benefit belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="benefits",
                to="schemes.plan",
            ),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="card_code",
            field=models.CharField(
                help_text="Unique 3-character alphanumeric code for the scheme (e.g., ABC, X12).",
                max_length=3,
                unique=True,
                validators=[apps.core.utils.validators.CardCodeValidator()],
            ),
        ),
    ]
