# Generated by Django 5.1.4 on 2025-10-31 13:08

from django.db import migrations
from collections import Counter


def fix_duplicate_plan_names(apps, schema_editor):
    """Fix duplicate plan names by appending index to duplicates."""
    Plan = apps.get_model("schemes", "Plan")

    # Get all plan names
    plans = Plan.objects.all().order_by('created_at')
    name_counter = Counter()

    for plan in plans:
        original_name = plan.plan_name
        name_counter[original_name] += 1

        # If this is a duplicate, append the count
        if name_counter[original_name] > 1:
            new_name = f"{original_name} {name_counter[original_name]}"
            plan.plan_name = new_name
            plan.save(update_fields=['plan_name'])


class Migration(migrations.Migration):
    dependencies = [
        ("schemes", "0007_alter_benefit_plan_alter_scheme_card_code"),
    ]

    operations = [
        migrations.RunPython(fix_duplicate_plan_names, migrations.RunPython.noop),
    ]
