# Generated by Django 5.1.4 on 2025-10-31 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_alter_company_phone_number"),
        ("schemes", "0008_fix_duplicate_plan_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefit",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Plan this benefit belongs to.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="benefits",
                to="schemes.plan",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="plan_name",
            field=models.CharField(
                help_text="Name of the plan.", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="company",
            field=models.ForeignKey(
                help_text="Associated company.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schemes",
                to="companies.company",
            ),
        ),
    ]
