# Generated by Django 5.1.4 on 2025-11-06 13:08

import apps.core.utils.generators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("schemes", "0009_alter_benefit_plan_alter_plan_plan_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemePeriod",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.core.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When record was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When record was last updated."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        help_text="Business or operational status of this record.",
                        max_length=10,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Indicates if record is soft deleted."
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="When record was soft deleted.", null=True
                    ),
                ),
                (
                    "period_number",
                    models.PositiveIntegerField(
                        help_text="Sequential period number (1 for initial, 2+ for renewals)."
                    ),
                ),
                ("start_date", models.DateField(help_text="Period start date.")),
                ("end_date", models.DateField(help_text="Period end date.")),
                (
                    "termination_date",
                    models.DateField(
                        blank=True,
                        help_text="Actual termination date (may differ from end_date).",
                        null=True,
                    ),
                ),
                (
                    "limit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Coverage or limit amount for this period.",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "renewal_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when this renewal was created.",
                        null=True,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Is this the current active period for the scheme?",
                    ),
                ),
                (
                    "changes_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary of changes from previous period (JSON).",
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, help_text="Period remarks.", max_length=500
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheme Period",
                "verbose_name_plural": "Scheme Periods",
                "db_table": "scheme_periods",
                "ordering": ["-period_number"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="schemeitem",
            name="unique_scheme_item",
        ),
        migrations.RemoveIndex(
            model_name="schemeitem",
            name="scheme_item_scheme__9e2c76_idx",
        ),
        migrations.AddField(
            model_name="scheme",
            name="is_renewable",
            field=models.BooleanField(
                default=True, help_text="Can this scheme be renewed?"
            ),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="DEPRECATED: Use SchemePeriod", null=True
            ),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="limit_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="DEPRECATED: Use SchemePeriod",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="remark",
            field=models.TextField(
                blank=True,
                help_text="Additional remarks about the scheme.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="DEPRECATED: Use SchemePeriod", null=True
            ),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="termination_date",
            field=models.DateField(
                blank=True, help_text="DEPRECATED: Use SchemePeriod", null=True
            ),
        ),
        migrations.AlterField(
            model_name="schemeitem",
            name="scheme",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED: Use scheme_period instead",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="old_items",
                to="schemes.scheme",
            ),
        ),
        migrations.AlterModelTable(
            name="scheme",
            table="schemes",
        ),
        migrations.AddField(
            model_name="schemeperiod",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted the record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schemeperiod",
            name="renewed_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Previous period this was renewed from.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renewed_to",
                to="schemes.schemeperiod",
            ),
        ),
        migrations.AddField(
            model_name="schemeperiod",
            name="scheme",
            field=models.ForeignKey(
                help_text="Parent scheme this period belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="schemes.scheme",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="schemeitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="schemeitem",
            name="scheme_period",
            field=models.ForeignKey(
                blank=True,
                help_text="Scheme period this item belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="schemes.schemeperiod",
            ),
        ),
        migrations.AddConstraint(
            model_name="schemeitem",
            constraint=models.UniqueConstraint(
                fields=("scheme_period", "content_type", "object_id"),
                name="unique_scheme_period_item",
            ),
        ),
        migrations.AddIndex(
            model_name="schemeperiod",
            index=models.Index(
                fields=["scheme", "is_current"], name="scheme_peri_scheme__1c6d98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schemeperiod",
            index=models.Index(
                fields=["start_date", "end_date"], name="scheme_peri_start_d_3e4ff8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="schemeperiod",
            unique_together={("scheme", "period_number")},
        ),
    ]
