# Generated by Django 5.1.4 on 2025-11-06 13:08

from django.db import migrations


def migrate_schemes_to_periods(apps, schema_editor):
    """
    Migrate existing Scheme records to use SchemePeriod model.

    For each existing scheme with date/limit data, create an initial SchemePeriod.
    Then link existing SchemeItems to those new periods.
    """
    Scheme = apps.get_model('schemes', 'Scheme')
    SchemePeriod = apps.get_model('schemes', 'SchemePeriod')
    SchemeItem = apps.get_model('schemes', 'SchemeItem')

    schemes_migrated = 0
    items_migrated = 0

    for scheme in Scheme.objects.all():
        # Check if this scheme has old data to migrate
        if scheme.start_date and scheme.end_date and scheme.limit_amount:
            # Check if period already exists (in case migration is re-run)
            existing_period = SchemePeriod.objects.filter(scheme=scheme).first()

            if not existing_period:
                # Create initial period from scheme's existing data
                period = SchemePeriod.objects.create(
                    scheme=scheme,
                    period_number=1,
                    start_date=scheme.start_date,
                    end_date=scheme.end_date,
                    termination_date=scheme.termination_date,
                    limit_amount=scheme.limit_amount,
                    is_current=True,
                    renewed_from=None,
                    renewal_date=None,
                    remark="Migrated from original scheme data",
                    status=scheme.status,
                    # Preserve creation timestamp
                    created_at=scheme.created_at,
                )
                schemes_migrated += 1
                print(f"✓ Created period for scheme '{scheme.scheme_name}' (ID: {scheme.id})")
            else:
                period = existing_period
                print(f"⚠ Period already exists for scheme '{scheme.scheme_name}' (ID: {scheme.id})")

            # Migrate SchemeItems for this scheme
            items = SchemeItem.objects.filter(scheme=scheme, scheme_period__isnull=True)
            for item in items:
                item.scheme_period = period
                item.save(update_fields=['scheme_period'])
                items_migrated += 1

    print(f"\n=== Migration Summary ===")
    print(f"Schemes migrated: {schemes_migrated}")
    print(f"Items migrated: {items_migrated}")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - copy current period data back to scheme.
    """
    Scheme = apps.get_model('schemes', 'Scheme')
    SchemePeriod = apps.get_model('schemes', 'SchemePeriod')
    SchemeItem = apps.get_model('schemes', 'SchemeItem')

    for scheme in Scheme.objects.all():
        current_period = SchemePeriod.objects.filter(
            scheme=scheme, is_current=True
        ).first()

        if current_period:
            scheme.start_date = current_period.start_date
            scheme.end_date = current_period.end_date
            scheme.termination_date = current_period.termination_date
            scheme.limit_amount = current_period.limit_amount
            scheme.save(update_fields=[
                'start_date', 'end_date', 'termination_date', 'limit_amount'
            ])

            # Restore scheme FK on items
            items = SchemeItem.objects.filter(scheme_period=current_period)
            for item in items:
                item.scheme = scheme
                item.save(update_fields=['scheme'])


class Migration(migrations.Migration):
    dependencies = [
        ("schemes", "0010_schemeperiod_remove_schemeitem_unique_scheme_item_and_more"),
    ]

    operations = [
        migrations.RunPython(
            migrate_schemes_to_periods,
            reverse_migration
        ),
    ]
