# Generated by Django 5.1.4 on 2025-11-06 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Remove old temporary fields after data migration is complete."""

    dependencies = [
        ("schemes", "0011_migrate_schemes_to_periods"),
    ]

    operations = [
        # Remove old date/limit fields from Scheme
        migrations.RemoveField(
            model_name="scheme",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="scheme",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="scheme",
            name="termination_date",
        ),
        migrations.RemoveField(
            model_name="scheme",
            name="limit_amount",
        ),
        # Remove old scheme FK from SchemeItem
        migrations.RemoveField(
            model_name="schemeitem",
            name="scheme",
        ),
        # Make scheme_period non-nullable now that data is migrated
        migrations.AlterField(
            model_name="schemeitem",
            name="scheme_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="schemes.schemeperiod",
                help_text="Scheme period this item belongs to.",
            ),
        ),
    ]
