# Generated by Django 5.1.4 on 2025-11-06 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schemes", "0012_remove_old_scheme_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="schemeperiod",
            index=models.Index(
                fields=["scheme", "period_number"],
                name="scheme_peri_scheme__1720a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="schemeperiod",
            index=models.Index(
                fields=["renewed_from"], name="scheme_peri_renewed_3b2768_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="schemeperiod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True), ("is_deleted", False)),
                fields=("scheme",),
                name="unique_current_period_per_scheme",
            ),
        ),
    ]
