# Generated by Django 5.2.7 on 2025-10-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medical_catalog",
            "0002_alter_labtest_options_alter_hospitalitemprice_amount_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hospitalitemprice",
            options={
                "verbose_name": "Hospital Item Price",
                "verbose_name_plural": "Hospital Item Prices",
            },
        ),
        migrations.AlterField(
            model_name="hospitalitemprice",
            name="object_id",
            field=models.CharField(max_length=25),
        ),
    ]
