# Generated by Django 5.2.7 on 2025-10-14 12:03

import apps.core.utils.generators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.CharField(default=apps.core.utils.generators.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When record was last updated.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', help_text='Business or operational status of this record.', max_length=10)),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if record is soft deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When record was soft deleted.', null=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('branch_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='providers.hospital')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'db_table': 'hospitals',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.CharField(default=apps.core.utils.generators.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When record was last updated.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', help_text='Business or operational status of this record.', max_length=10)),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if record is soft deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When record was soft deleted.', null=True)),
                ('name', models.CharField(max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='providers.hospital')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'doctors',
            },
        ),
    ]
