# Generated by Django 5.2.7 on 2025-10-14 14:45

import apps.core.utils.generators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
        migrations.CreateModel(
            name='DoctorHospitalAffiliation',
            fields=[
                ('id', models.CharField(default=apps.core.utils.generators.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When record was last updated.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', help_text='Business or operational status of this record.', max_length=10)),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if record is soft deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When record was soft deleted.', null=True)),
                ('role', models.CharField(blank=True, help_text='Role at this hospital (e.g., Consultant, Resident)', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Marks doctor’s main hospital')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.hospital')),
            ],
            options={
                'unique_together': {('doctor', 'hospital')},
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(related_name='doctors', through='providers.DoctorHospitalAffiliation', to='providers.hospital'),
        ),
    ]
