# Generated by Django 5.1.4 on 2025-10-31 10:28

import apps.core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_alter_company_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="phone_number",
            field=models.CharField(
                help_text="Primary phone number in format: +[country code][number] (e.g., +12345678900).",
                max_length=20,
                validators=[apps.core.utils.validators.PhoneNumberValidator()],
            ),
        ),
    ]
