# Generated by Django 5.1.4 on 2025-10-31 10:28

import apps.core.utils.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_alter_company_phone_number"),
        ("members", "0001_initial"),
        ("schemes", "0007_alter_benefit_plan_alter_scheme_card_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="company",
            field=models.ForeignKey(
                help_text="Associated company",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number in format: +[country code][number] (e.g., +12345678900).",
                max_length=20,
                validators=[apps.core.utils.validators.PhoneNumberValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="scheme",
            field=models.ForeignKey(
                help_text="Insurance scheme",
                on_delete=django.db.models.deletion.PROTECT,
                to="schemes.scheme",
            ),
        ),
    ]
