# Generated by Django 5.2.7 on 2025-10-04 21:09

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.CharField(default=base.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when this record was last updated.')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag or status marker.')),
                ('type_name', models.CharField(help_text='Name of the company type.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the company type.', max_length=500)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('DELETED', 'Deleted')], default='ACTIVE', help_text='Status of the company type.', max_length=10)),
            ],
            options={
                'verbose_name': 'Company Type',
                'verbose_name_plural': 'Company Types',
                'db_table': 'nm_company_types',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(default=base.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when this record was last updated.')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag or status marker.')),
                ('company_name', models.CharField(help_text='Name of the company.', max_length=255)),
                ('contact_person', models.CharField(help_text='Contact person for the company.', max_length=255)),
                ('company_address', models.TextField(help_text='Address of the company.')),
                ('phone_number', models.CharField(help_text='Phone number of the company.', max_length=20)),
                ('email', models.EmailField(help_text='Email address of the company.', max_length=255)),
                ('website', models.URLField(blank=True, help_text='Website of the company.', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('DELETED', 'Deleted')], default='ACTIVE', help_text='Status of the company.', max_length=10)),
                ('remark', models.TextField(blank=True, help_text='Additional remarks about the company.', max_length=500)),
                ('company_type', models.ForeignKey(help_text='Type of the company.', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='base.companytype')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'nm_companies',
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.CharField(default=base.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when this record was last updated.')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag or status marker.')),
                ('scheme_name', models.CharField(help_text='Name of the scheme.', max_length=255)),
                ('card_code', models.CharField(help_text='Unique code for the scheme.', max_length=3, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the scheme.', max_length=500)),
                ('start_date', models.DateField(help_text='Start date of the scheme.')),
                ('end_date', models.DateField(help_text='End date of the scheme.')),
                ('termination_date', models.DateField(blank=True, help_text='Termination date of the scheme, if applicable.', null=True)),
                ('limit_amount', models.DecimalField(decimal_places=2, help_text='Limit amount for the scheme.', max_digits=15)),
                ('family_status', models.BooleanField(choices=[(True, 'Applicable'), (False, 'Not Applicable')], default=False, help_text='Indicates if the scheme is applicable for family.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('DELETED', 'Deleted')], default='ACTIVE', help_text='Status of the scheme.', max_length=10)),
                ('remark', models.TextField(blank=True, help_text='Additional remarks about the scheme.', max_length=500)),
                ('company', models.ForeignKey(help_text='Company associated with the scheme.', on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='base.company')),
            ],
            options={
                'verbose_name': 'Scheme',
                'verbose_name_plural': 'Schemes',
                'db_table': 'nm_schemes',
            },
        ),
    ]
